import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'surface-tint': '#3755c3',
                'on-primary': '#ffffff',
                'on-tertiary-fixed': '#2a1700',
                'secondary': '#006c49',
                'surface-container': '#e5eeff',
                'surface-container-high': '#dce9ff',
                'on-primary-fixed-variant': '#173bab',
                'on-surface-variant': '#444653',
                'error-container': '#ffdad6',
                'surface-container-highest': '#d3e4fe',
                'on-secondary-container': '#00714d',
                'secondary-fixed': '#6ffbbe',
                'on-error-container': '#93000a',
                'on-primary-container': '#a8b8ff',
                'secondary-fixed-dim': '#4edea3',
                'surface-container-low': '#eff4ff',
                'surface-variant': '#d3e4fe',
                'on-error': '#ffffff',
                'inverse-surface': '#213145',
                'inverse-on-surface': '#eaf1ff',
                'tertiary-container': '#6b4200',
                'primary': '#00288e',
                'surface-container-lowest': '#ffffff',
                'primary-container': '#1e40af',
                'on-primary-fixed': '#001453',
                'on-surface': '#0b1c30',
                'primary-fixed': '#dde1ff',
                'background': '#f8f9ff',
                'error': '#ba1a1a',
                'inverse-primary': '#b8c4ff',
                'outline': '#757684',
                'surface-bright': '#f8f9ff',
                'on-tertiary-container': '#ffa929',
                'tertiary-fixed-dim': '#ffb95f',
                'secondary-container': '#6cf8bb',
                'outline-variant': '#c4c5d5',
                'on-secondary': '#ffffff',
                'surface-dim': '#cbdbf5',
                'on-background': '#0b1c30',
                'on-secondary-fixed': '#002113',
                'surface': '#f8f9ff',
                'tertiary': '#4c2e00',
                'on-tertiary': '#ffffff',
                'on-secondary-fixed-variant': '#005236',
                'on-tertiary-fixed-variant': '#653e00',
                'primary-fixed-dim': '#b8c4ff',
                'tertiary-fixed': '#ffddb8',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                xs: '4px',
                sm: '12px',
                md: '16px',
                base: '8px',
                lg: '24px',
                xl: '32px',
                '2xl': '48px',
                gutter: '24px',
                margin: '32px',
            },
            fontFamily: {
                'display-lg': ['Inter', 'sans-serif'],
                'headline-lg': ['Inter', 'sans-serif'],
                'headline-lg-mobile': ['Inter', 'sans-serif'],
                'title-md': ['Inter', 'sans-serif'],
                'body-md': ['Inter', 'sans-serif'],
                'body-sm': ['Inter', 'sans-serif'],
                'label-caps': ['Inter', 'sans-serif'],
                'code-sm': ['Inter', 'sans-serif'],
                sans: ['Inter', 'sans-serif'],
            },
            fontSize: {
                'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
                'code-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
            },
        },
    },

    plugins: [forms],
};
